// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AdminPortal {
	
	
	public partial class FormDetails {
		
		protected System.Web.UI.HtmlControls.HtmlForm form;
		
		protected System.Web.UI.WebControls.Button GenerateReportButton;
		
		protected System.Web.UI.WebControls.Button CompleteButton;
		
		protected System.Web.UI.WebControls.Button DeleteButton;
		
		protected System.Web.UI.WebControls.Button PayButton;
	}
}
