// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AdminPortal {
	
	
	public partial class Login {
		
		protected System.Web.UI.HtmlControls.HtmlForm LoginForm;
		
		protected System.Web.UI.WebControls.Panel ErrorMessage;
		
		protected AdminPortal.FormField Username;
		
		protected AdminPortal.FormField Password;
		
		protected System.Web.UI.WebControls.Button SubmitButton;
	}
}
